//! Context pack Markdown rendering

use crate::domain::{Chunk, FileDisposition, FileInfo, ScanStats};
use crate::utils::format_with_commas;
use chrono::Utc;
use serde_json::Value as JsonValue;
use std::collections::HashMap;
use std::path::Path;

/// Arguments for `render_context_pack`.
#[allow(missing_docs)]
pub struct ContextPackCtx<'a> {
    pub root_path: &'a Path,
    pub files: &'a [FileInfo],
    pub chunks: &'a [Chunk],
    pub stats: &'a ScanStats,
    pub tree: &'a str,
    pub manifest_info: &'a HashMap<String, JsonValue>,
    pub dispositions: &'a [FileDisposition],
    pub full_inventory: bool,
    pub include_timestamp: bool,
}

impl<'a> ContextPackCtx<'a> {
    /// Render the context pack from this context.
    pub fn render(&self) -> String {
        render_context_pack(
            self.root_path,
            self.files,
            self.chunks,
            self.stats,
            self.tree,
            self.manifest_info,
            self.dispositions,
            self.full_inventory,
            self.include_timestamp,
        )
    }
}

/// Renders the context pack markdown document.
///
/// # Arguments
/// * `root_path` - Path to the repository root
/// * `files` - List of files included in the pack
/// * `chunks` - List of chunks to include
/// * `stats` - Scan statistics
/// * `tree` - Directory tree string
/// * `manifest_info` - Manifest information from various build files
/// * `include_timestamp` - Whether to include generation timestamp
///
/// # Returns
/// Markdown-formatted context pack string
#[allow(clippy::too_many_arguments)]
pub fn render_context_pack(
    root_path: &Path,
    files: &[FileInfo],
    chunks: &[Chunk],
    stats: &ScanStats,
    tree: &str,
    manifest_info: &HashMap<String, JsonValue>,
    dispositions: &[FileDisposition],
    full_inventory: bool,
    include_timestamp: bool,
) -> String {
    let mut out = String::new();

    // ── Header ──────────────────────────────────────────────────────────────
    out.push_str(&format!(
        "# Repository Context Pack: {}\n\n",
        root_path.file_name().and_then(|n| n.to_str()).unwrap_or("repo")
    ));
    if include_timestamp {
        out.push_str(&format!(
            "> Generated by repo-context on {}\n",
            Utc::now().format("%Y-%m-%d %H:%M:%S UTC")
        ));
    } else {
        out.push_str("> Generated by repo-context\n");
    }
    // Summary line: Files | Chunks | Size (matches Python _render_header)
    out.push_str(&format!(
        "> Files: {} | Chunks: {} | Size: {} bytes\n",
        stats.files_included,
        chunks.len(),
        format_with_commas(stats.total_bytes_included)
    ));
    out.push_str("\n---\n\n");

    render_inventory(&mut out, stats, files, dispositions, full_inventory);

    // ── Repository Overview ──────────────────────────────────────────────────
    out.push_str("## 📋 Repository Overview\n\n");

    // Project name and description from manifest_info (Python lines 135-139)
    if let Some(JsonValue::String(name)) = manifest_info.get("name") {
        out.push_str(&format!("**Project:** {}\n\n", name));
    }
    if let Some(JsonValue::String(description)) = manifest_info.get("description") {
        out.push_str(&format!("**Description:** {}\n\n", description));
    }

    // Language summary (top 5, bold paragraph — matches Python renderer.py lines 144-149)
    let mut lang_counts: Vec<_> = stats.languages_detected.iter().collect();
    lang_counts.sort_by(|a, b| b.1.cmp(a.1).then_with(|| a.0.cmp(b.0)));
    if !lang_counts.is_empty() {
        let top = lang_counts
            .iter()
            .take(5)
            .map(|(lang, count)| format!("{} ({})", lang, count))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("\n**Languages:** {}\n\n", top));
    }

    // Entrypoints (sorted, non-indented bullets — matches Python renderer.py lines 152-156)
    let mut entrypoints: Vec<&str> = files
        .iter()
        .filter(|f| f.tags.contains("entrypoint"))
        .map(|f| f.relative_path.as_str())
        .collect();
    entrypoints.sort();
    if !entrypoints.is_empty() {
        out.push_str("\n**Entrypoints:**\n");
        for ep in entrypoints.iter().take(10) {
            out.push_str(&format!("- `{}`\n", ep));
        }
    }

    // Available Commands from package.json scripts (matches Python _render_overview lines 159-168)
    if let Some(JsonValue::Object(scripts)) = manifest_info.get("scripts") {
        let known_cmds = ["build", "test", "start", "dev", "lint"];
        let present: Vec<(&str, &str)> = known_cmds
            .iter()
            .filter_map(|cmd| scripts.get(*cmd).and_then(|v| v.as_str()).map(|val| (*cmd, val)))
            .collect();
        if !present.is_empty() {
            out.push_str("\n**Available Commands:**\n");
            for (cmd, val) in present {
                if val.len() > 60 {
                    out.push_str(&format!("- `{}`: `{}...`\n", cmd, &val[..60]));
                } else {
                    out.push_str(&format!("- `{}`: `{}`\n", cmd, val));
                }
            }
        }
    }

    // README excerpt — find the highest-priority readme file and show first 15 meaningful lines.
    // Matches Python renderer.py lines 170-190.
    // Uses already-processed (redacted) chunks to avoid re-reading raw source from disk.
    if let Some(readme) = files.iter().find(|f| f.is_readme) {
        let readme_chunks: Vec<&Chunk> =
            chunks.iter().filter(|c| c.path == readme.relative_path).collect();
        if let Some(first_chunk) = readme_chunks.first() {
            let content = &first_chunk.content;
            let readme_lines: Vec<&str> = content.lines().collect();
            let mut excerpt_lines: Vec<&str> = Vec::new();
            let mut in_content = false;
            for line in readme_lines.iter().take(50) {
                let trimmed = line.trim();
                // Skip badges only before content begins (Python: badge check before in_content=True)
                if !in_content {
                    if trimmed.starts_with("![") || trimmed.starts_with("[![") {
                        continue;
                    }
                    if trimmed.is_empty() {
                        continue;
                    }
                    in_content = true;
                }
                excerpt_lines.push(line);
                if excerpt_lines.len() >= 15 {
                    break;
                }
            }
            if !excerpt_lines.is_empty() {
                let excerpt = excerpt_lines.join("\n");
                out.push_str(&format!("\n**README Excerpt:**\n\n{}\n", excerpt));
            }
        }
    }
    out.push('\n');

    // ── Directory Tree ───────────────────────────────────────────────────────
    out.push_str("## 📁 Directory Structure\n\n");
    out.push_str("```\n");
    out.push_str(tree);
    out.push_str("\n```\n\n*⭐ = Important file*\n\n");

    // ── Key Files ────────────────────────────────────────────────────────────
    // Python groups into Documentation / Configuration / Entrypoints (5 per category).
    out.push_str("## 🔑 Key Files\n");

    #[allow(clippy::type_complexity)]
    let categories: &[(&str, Box<dyn Fn(&&FileInfo) -> bool>)] = &[
        ("Documentation", Box::new(|f: &&FileInfo| f.is_doc)),
        ("Configuration", Box::new(|f: &&FileInfo| f.is_config)),
        ("Entrypoints", Box::new(|f: &&FileInfo| f.tags.contains("entrypoint"))),
    ];

    for (category, predicate) in categories {
        let cat_files: Vec<&FileInfo> = files.iter().filter(|f| predicate(f)).take(5).collect();
        if !cat_files.is_empty() {
            out.push_str(&format!("\n### {}\n", category));
            for file in cat_files {
                let pct = (file.priority * 100.0).round() as u64;
                out.push_str(&format!("- `{}` ({}%)\n", file.relative_path, pct));
            }
        }
    }
    out.push('\n');

    // ── Code Map ────────────────────────────────────────────────────────────
    // Group files by language, skip pure text/markdown, top 5 languages.
    let mut files_by_lang: HashMap<&str, Vec<&FileInfo>> = HashMap::new();
    for file in files {
        files_by_lang.entry(file.language.as_str()).or_default().push(file);
    }
    let mut sorted_langs: Vec<_> = files_by_lang.iter().collect();
    sorted_langs.sort_by(|a, b| b.1.len().cmp(&a.1.len()).then_with(|| a.0.cmp(b.0)));

    let code_map_langs: Vec<_> = sorted_langs
        .iter()
        .filter(|(lang, _)| !matches!(**lang, "text" | "markdown"))
        .take(5)
        .collect();

    if !code_map_langs.is_empty() {
        out.push_str("## 🗺️ Code Map\n");
        for (lang, lang_files) in &code_map_langs {
            out.push_str(&format!("\n### {} ({} files)\n", capitalize(lang), lang_files.len()));

            // Group by directory
            let mut dirs: HashMap<String, Vec<&FileInfo>> = HashMap::new();
            for f in lang_files.iter() {
                let dir = Path::new(&f.relative_path)
                    .parent()
                    .and_then(|p| p.to_str())
                    .map(|s| if s.is_empty() { "(root)".to_string() } else { s.to_string() })
                    .unwrap_or_else(|| "(root)".to_string());
                dirs.entry(dir).or_default().push(f);
            }

            let mut sorted_dirs: Vec<_> = dirs.iter().collect();
            sorted_dirs.sort_by_key(|(d, _)| d.as_str());

            for (dir_path, dir_files) in sorted_dirs.iter().take(10) {
                out.push_str(&format!("\n**{}/**\n", dir_path));
                let mut sorted_files: Vec<&&FileInfo> = dir_files.iter().collect();
                sorted_files.sort_by_key(|f| {
                    Path::new(&f.relative_path)
                        .file_name()
                        .and_then(|n| n.to_str())
                        .unwrap_or("")
                        .to_string()
                });
                for f in sorted_files.iter().take(10) {
                    let fname = Path::new(&f.relative_path)
                        .file_name()
                        .and_then(|n| n.to_str())
                        .unwrap_or(&f.relative_path);
                    out.push_str(&format!("- `{}`\n", fname));
                }
                if dir_files.len() > 10 {
                    out.push_str(&format!("- *...and {} more*\n", dir_files.len() - 10));
                }
            }
        }
        out.push('\n');
    }

    // ── File Contents ────────────────────────────────────────────────────────
    out.push_str("## 📄 File Contents\n\n");

    // Group chunks by file path, sorted by file priority then path.
    let file_priorities: HashMap<&str, f64> =
        files.iter().map(|f| (f.relative_path.as_str(), f.priority)).collect();
    let mut chunks_by_file: HashMap<&str, Vec<&Chunk>> = HashMap::new();
    for chunk in chunks {
        chunks_by_file.entry(chunk.path.as_str()).or_default().push(chunk);
    }

    let mut sorted_paths: Vec<&&str> = chunks_by_file.keys().collect();
    sorted_paths.sort_by(|a, b| {
        let pa = file_priorities.get(**a).copied().unwrap_or(0.0);
        let pb = file_priorities.get(**b).copied().unwrap_or(0.0);
        pb.partial_cmp(&pa).unwrap_or(std::cmp::Ordering::Equal).then_with(|| a.cmp(b))
    });

    for path in sorted_paths {
        let file_chunks = chunks_by_file.get(path).unwrap();
        let mut sorted_chunks: Vec<&&Chunk> = file_chunks.iter().collect();
        sorted_chunks.sort_by(|a, b| a.start_line.cmp(&b.start_line).then_with(|| a.id.cmp(&b.id)));

        let lang = sorted_chunks.first().map(|c| c.language.as_str()).unwrap_or("text");
        let priority = file_priorities.get(*path).copied().unwrap_or(0.5);

        // Per-file header with metadata
        out.push_str(&format!("### `{}`\n\n", path));
        out.push_str(&format!(
            "*Priority: {:.0}% | Language: {} | Chunks: {}*\n\n",
            priority * 100.0,
            lang,
            file_chunks.len()
        ));

        for chunk in dedupe_overlapping_chunks(sorted_chunks.into_iter().copied().collect()) {
            let mut notes: Vec<String> = chunk
                .tags
                .iter()
                .filter_map(|tag| {
                    if let Some(reason) = tag.strip_prefix("reason:") {
                        return Some(reason.to_string());
                    }
                    if let Some(stitch) = tag.strip_prefix("stitch:") {
                        return Some(format!("stitched:{stitch}"));
                    }
                    None
                })
                .collect();
            notes.sort();
            notes.dedup();
            if notes.is_empty() {
                out.push_str(&format!("**Lines {}-{}:**\n\n", chunk.start_line, chunk.end_line));
            } else {
                out.push_str(&format!(
                    "**Lines {}-{}:** `[{}]`\n\n",
                    chunk.start_line,
                    chunk.end_line,
                    notes.join(" | ")
                ));
            }
            out.push_str(&format!("```{}\n", escape_fence_lang(&chunk.language)));
            let trimmed = chunk.content.trim_end();
            out.push_str(trimmed);
            // Escape any trailing backtick sequences in content to prevent fence-breaking.
            out.push('\n');
            out.push_str("```\n\n");
        }
    }

    out
}

fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
    }
}

/// Escape Markdown table cell content to prevent formatting corruption.
fn escape_table_cell(s: &str) -> String {
    s.replace('|', "\\|").replace('\n', " ").replace('\r', "")
}

/// Sanitize a language identifier for use in a Markdown code fence.
fn escape_fence_lang(lang: &str) -> String {
    lang.chars()
        .filter(|c| c.is_alphanumeric() || *c == '_' || *c == '-' || *c == '+')
        .take(20)
        .collect()
}

fn render_inventory(
    out: &mut String,
    stats: &ScanStats,
    files: &[FileInfo],
    dispositions: &[FileDisposition],
    full_inventory: bool,
) {
    out.push_str("## Repository Inventory\n\n");
    out.push_str(&format!("- total files discovered: {}\n", stats.files_discovered));
    out.push_str(&format!("- candidate files: {}\n", stats.candidate_files));
    out.push_str(&format!("- files included in prompt: {}\n", stats.files_selected_prompt));
    out.push_str(&format!("- files included in RAG: {}\n", stats.files_selected_rag));
    out.push_str(&format!(
        "- tests count: {}\n",
        files.iter().filter(|f| f.tags.contains("test")).count()
    ));
    out.push_str(&format!("- docs count: {}\n", files.iter().filter(|f| f.is_doc).count()));
    let mut by_reason: HashMap<&str, usize> = HashMap::new();
    for d in dispositions {
        *by_reason.entry(d.reason.as_str()).or_insert(0) += 1;
    }
    let mut reasons: Vec<_> = by_reason.into_iter().collect();
    reasons.sort_by(|a, b| a.0.cmp(b.0));
    if !reasons.is_empty() {
        out.push_str("- skipped/dropped by reason: ");
        out.push_str(
            &reasons.iter().map(|(r, c)| format!("{r}={c}")).collect::<Vec<_>>().join(", "),
        );
        out.push('\n');
    }
    out.push_str(
        "\n| path | language | role/tags | priority | tokens | prompt/rag/disposition |\n",
    );
    out.push_str("| --- | --- | --- | ---: | ---: | --- |\n");
    let limit = if full_inventory { usize::MAX } else { 100 };
    for d in dispositions.iter().take(limit) {
        out.push_str(&format!(
            "| `{}` | {} | {} | {} | {} | {}/{}/{} |\n",
            escape_table_cell(&d.path),
            escape_table_cell(&d.language),
            escape_table_cell(d.notes.as_deref().unwrap_or("")),
            d.priority.map(|p| format!("{p:.3}")).unwrap_or_default(),
            d.token_estimate.map(|t| t.to_string()).unwrap_or_default(),
            if d.included_in_prompt { "prompt" } else { "-" },
            if d.included_in_rag { "rag" } else { "-" },
            d.reason.as_str()
        ));
    }
    if dispositions.len() > limit {
        out.push_str(&format!(
            "\n*Inventory table capped at {limit} rows; report JSON contains the complete inventory.*\n"
        ));
    }
    out.push('\n');
}

fn dedupe_overlapping_chunks(chunks: Vec<&Chunk>) -> Vec<Chunk> {
    let mut rendered = Vec::new();
    let mut next_line = 1usize;
    for chunk in chunks {
        if chunk.end_line < next_line {
            continue;
        }
        let skip = next_line.saturating_sub(chunk.start_line);
        let content = if skip == 0 {
            chunk.content.clone()
        } else {
            chunk.content.split_inclusive('\n').skip(skip).collect()
        };
        if content.trim().is_empty() {
            continue;
        }
        let mut deduped = chunk.clone();
        deduped.start_line = chunk.start_line.max(next_line);
        deduped.content = content;
        next_line = chunk.end_line + 1;
        rendered.push(deduped);
    }
    rendered
}

#[cfg(test)]
mod tests {
    use super::dedupe_overlapping_chunks;
    use crate::domain::Chunk;
    use std::collections::BTreeSet;

    fn chunk(id: &str, start: usize, end: usize, content: &str) -> Chunk {
        Chunk {
            id: id.to_string(),
            path: "src/lib.rs".to_string(),
            language: "rust".to_string(),
            start_line: start,
            end_line: end,
            content: content.to_string(),
            priority: 0.8,
            tags: BTreeSet::new(),
            token_estimate: 10,
            file_id: "f".to_string(),
            chunk_index: 0,
            chunks_in_file: 2,
            byte_start: None,
            byte_end: None,
            content_sha256: String::new(),
            file_sha256: String::new(),
        }
    }

    #[test]
    fn context_pack_dedupes_overlapping_line_ranges() {
        let first = chunk("a", 1, 3, "line1\nline2\nline3\n");
        let second = chunk("b", 3, 5, "line3\nline4\nline5\n");

        let deduped = dedupe_overlapping_chunks(vec![&first, &second]);

        assert_eq!(deduped.len(), 2);
        assert_eq!(deduped[1].start_line, 4);
        assert_eq!(deduped[1].content, "line4\nline5\n");
    }
}
